### ISSUE TITLE
Altoholic v10.2.013 (retail) - Datastore_Auctions LUA error still happens when bidding on bid-only auctions.

### ISSUE THREAD

**Issue by R-Adrian** [Thaoky/Altoholic_Retail#11]
issue 1 for Datastore_Auctions https://github.com/Thaoky/DataStore_Auctions/issues/1  can still happen:

line 100 in the new DataStore_Auctions_Retail.lua file:

```
		-- review item.name ? item.quantity ?
		TableInsert(bidsList[charID], format("%s|%s|%s|%s|%s|%s|%s", 
			AHZone, itemID, info.quantity or 1, info.bidder or "", info.bidAmount or 0, info.buyoutAmount, info.timeLeft))	
```	

and the same fix applies:   
the buyoutAmount parameter should have "or 0" added to it too and it becomes: `info.buyoutAmount or 0`

**Comment by Thaoky** [comment]
Fixed in DataStore_Auctions, thanks for reporting !
