### ISSUE TITLE
Altoholic v10.2.013 (retail)  - Bad Argument 1# "Pairs" when logging into a character

### ISSUE THREAD

**Issue by crypticasden** [Thaoky/Altoholic_Retail#15]
Describe the bug and post the error message, if there is one:

Message: Interface/AddOns/Altoholic/Core.lua:456: bad argument #1 to 'pairs' (table expected, got nil)
Time: Fri May 24 09:36:54 2024
Count: 1
Stack: Interface/AddOns/Altoholic/Core.lua:456: bad argument #1 to 'pairs' (table expected, got nil)
[string "=[C]"]: in function `pairs'
[string "@Interface/AddOns/Altoholic/Core.lua"]:456: in function `MoveData'
[string "@Interface/AddOns/Altoholic/Core.lua"]:463: in function `callback'
[string "@Interface/AddOns/DataStore/Events/Loading.lua"]:25: in function <Interface/AddOns/DataStore/Events/Loading.lua:18>

Locals: (*temporary) = nil
(*temporary) = "table expected, got nil"
 = <function> defined =[C]:-1

To Reproduce:

steps to reproduce: 1.Log on a character after the addon version upgrade
		                2.Error happens upon logon when loading addons initially 

![image](https://github.com/Thaoky/Altoholic_Retail/assets/29047474/7435181c-4f9d-413d-9386-76e649358152)

 

Addons:
Altoholic v10.2.013
DataStore v2024.05.20

**Comment by Thaoky** [comment]
Fixed in next release
