### ISSUE TITLE
Altoholic v10.2.014 (retail) - Unable to delete characters and reset all data; "yes" button is broken

### ISSUE THREAD

**Issue by avarose8910** [Thaoky/Altoholic_Retail#16]
Already deleted and reinstalled the addon and all DataStore addons, as well as the SavedVariables files

18x DataStore/API/Core.lua:304: attempt to index field 'db' (a nil value)
[string "@DataStore/API/Core.lua"]:304: in function `IterateDBModules'
[string "@DataStore/DataStore.lua"]:317: in function `DeleteCharacter'
[string "@Altoholic_Summary/Columns_CharacterInformation.lua"]:74: in function `onClickButton1'
[string "@AddonFactory/Templates/MessageBox.lua"]:35: in function `Button_OnClick'
[string "*MessageBox.xml:53_OnClick"]:1: in function <[string "*MessageBox.xml:53_OnClick"]:1>

Locals:
self = <table> {
 GetCharacterID = <function> defined @DataStore/DataStore.lua:119
 IsCurrentPlayerKey = <function> defined @DataStore/DataStore.lua:195
 GuildBroadcast = <function> defined @DataStore/API/GuildComm.lua:163
 DeleteCharacter = <function> defined @DataStore/DataStore.lua:312
 GetCharacterDB = <function> defined @DataStore/API/Core.lua:217
 IsCharacterBasedMethod = <function> defined @DataStore/API/Core.lua:267
 DeleteGuild = <function> defined @DataStore/DataStore.lua:329
 GetCharacterKey = <function> defined @DataStore/DataStore.lua:123
 GetHashSize = <function> defined @DataStore/API/Utility.lua:6
 GetLocale = <function> defined @DataStore/API/Locale.lua:55
 CopyTable = <function> defined @DataStore/API/Utility.lua:50
 UpdateMyMemoryUsage = <function> defined @DataStore/Options.lua:170
 ThisCharID = 18
 SetLocale = <function> defined @DataStore/API/Locale.lua:42
 SetDefaults = <function> defined @DataStore/API/Core.lua:229
 GetModuleLastUpdateByKey = <function> defined @DataStore/API/Core.lua:334
 GetThisGuildKey = <function> defined @DataStore/DataStore.lua:291
 Enum = <table> {
 }
 GetOnlineGuildMembers = <function> defined @DataStore/API/GuildComm.lua:253
 RegisterMethod = <function> defined @DataStore/API/Core.lua:141
 RegisterModule = <function> defined @DataStore/API/Core.lua:161
 AddOrGetAutoID = <function> defined @DataStore/API/Utility.lua:90
 ClearAllData = <function> defined @DataStore/DataStore.lua:372
 GetGuilds = <function> defined @DataStore/DataStore.lua:257
 GetAccounts = <function> defined @DataStore/DataStore.lua:173
 IterateCharacters = <function> defined @DataStore/DataStore.lua:203
 StopListeningTo = <function> defined @DataStore/API/Core.lua:200
 SetupInfoPanel = <function> defined @DataStore/Options.lua:102
 GetGuildMemberAlts = <function> defined @DataStore/API/GuildComm.lua:246
 SetGuildBasedMethod = <function> defined @DataStore/API/Core.lua:275
 SetGuildCommCallbacks = <function> defined @DataStore/API/GuildComm.lua:227
 IsCurrentPlayer = <function> defined @DataStore/DataStore.lua:189
 GuildWhisper = <function> defined @DataStore/API/GuildComm.lua:155
 OnGuildComm = <function> defined @DataStore/Events/Comm.lua:70
 IsModuleEnabled = <function> defined @DataStore/API/Core.lua:293
 GetCharacter = <function> defined @DataStore/DataStore.lua:112
 IterateDBModules = <function> defined @DataStore/API/Core.lua:302
 StoreToSetAndList = <function> defined @DataStore/API/Utility.lua:112
 GetMethodOwner = <function> defined @DataStore/API/Core.lua:245
 ThisFaction = "Alliance"
 GetGuildFaction = <function> defined @DataStore/DataStore.lua:282
 ThisChar = "Johndoex"
 GetGuildMemberInfo = <function> defined @DataStore/API/GuildComm.lua:232
 OnUpdate = <function> defined @DataStore/Options.lua:227
 GetCharacterTable = <function> defined @DataStore/API/Core.lua:319
 GetNameOfMain = <function> defined @DataStore/API/GuildComm.lua:262
 SetDefaultLocale = <function> defined @DataStore/API/Locale.lua:35
 Frames = DataStoreFrames {
 }
 ListenTo = <function> defined @DataStore/API/Core.lua:199
 GetGuild = <function> defined @DataStore/DataStore.lua:242
 OnPlayerLogin = <function> defined @DataStore/Events/Loading.lua:50
 Print = <function> defined @DataStore/API/Core.lua:198
 ThisAccount = "Default"
 SetCheckBoxT

**Comment by justadakaje** [comment]
In trying to troubleshoot with Ava, I have a fresh install of the Altoholic addon, having never installed it before. Logged into first char and it is logged into the addon. I logged into a second char and still also see the first char. When I tried to delete the first char from addon while logged into the second, I also received similar error in BugSack:

`4x DataStore/API/Core.lua:304: attempt to index field 'db' (a nil value)
[string "@DataStore/API/Core.lua"]:304: in function `IterateDBModules'
[string "@DataStore/DataStore.lua"]:375: in function `ClearAllData'
[string "@Altoholic_Summary/TabSummary.lua"]:155: in function `onClickButton1'
[string "@AddonFactory/Templates/MessageBox.lua"]:35: in function `Button_OnClick'
[string "*MessageBox.xml:53_OnClick"]:1: in function <[string "*MessageBox.xml:53_OnClick"]:1>

Locals:
self = <table> {
 GetCharacterID = <function> defined @DataStore/DataStore.lua:119
 IsCurrentPlayerKey = <function> defined @DataStore/DataStore.lua:195
 GuildBroadcast = <function> defined @DataStore/API/GuildComm.lua:163
 DeleteCharacter = <function> defined @DataStore/DataStore.lua:312
 GetCharacterDB = <function> defined @DataStore/API/Core.lua:217
 IsCharacterBasedMethod = <function> defined @DataStore/API/Core.lua:267
 DeleteGuild = <function> defined @DataStore/DataStore.lua:329
 GetCharacterKey = <function> defined @DataStore/DataStore.lua:123
 GetHashSize = <function> defined @DataStore/API/Utility.lua:6
 GetLocale = <function> defined @DataStore/API/Locale.lua:55
 CopyTable = <function> defined @DataStore/API/Utility.lua:50
 UpdateMyMemoryUsage = <function> defined @DataStore/Options.lua:170
 ThisCharID = 1
 SetLocale = <function> defined @DataStore/API/Locale.lua:42
 SetDefaults = <function> defined @DataStore/API/Core.lua:229
 GetModuleLastUpdateByKey = <function> defined @DataStore/API/Core.lua:334
 GetThisGuildKey = <function> defined @DataStore/DataStore.lua:291
 Enum = <table> {
 }
 GetOnlineGuildMembers = <function> defined @DataStore/API/GuildComm.lua:253
 RegisterMethod = <function> defined @DataStore/API/Core.lua:141
 RegisterModule = <function> defined @DataStore/API/Core.lua:161
 AddOrGetAutoID = <function> defined @DataStore/API/Utility.lua:90
 ClearAllData = <function> defined @DataStore/DataStore.lua:372
 GetGuilds = <function> defined @DataStore/DataStore.lua:257
 GetAccounts = <function> defined @DataStore/DataStore.lua:173
 IterateCharacters = <function> defined @DataStore/DataStore.lua:203
 StopListeningTo = <function> defined @DataStore/API/Core.lua:200
 SetupInfoPanel = <function> defined @DataStore/Options.lua:102
 GetGuildMemberAlts = <function> defined @DataStore/API/GuildComm.lua:246
 SetGuildBasedMethod = <function> defined @DataStore/API/Core.lua:275
 SetGuildCommCallbacks = <function> defined @DataStore/API/GuildComm.lua:227
 IsCurrentPlayer = <function> defined @DataStore/DataStore.lua:189
 GuildWhisper = <function> defined @DataStore/API/GuildComm.lua:155
 OnGuildComm = <function> defined @DataStore/Events/Comm.lua:70
 IsModuleEnabled = <function> defined @DataStore/API/Core.lua:293
 GetCharacter = <function> defined @DataStore/DataStore.lua:112
 IterateDBModules = <function> defined @DataStore/API/Core.lua:302
 StoreToSetAndList = <function> defined @DataStore/API/Utility.lua:112
 GetMethodOwner = <function> defined @DataStore/API/Core.lua:245
 ThisFaction = "Horde"
 GetGuildFaction = <function> defined @DataStore/DataStore.lua:282
 ThisChar = "Kenestrasz"
 GetGuildMemberInfo = <function> defined @DataStore/API/GuildComm.lua:232
 OnUpdate = <function> defined @DataStore/Options.lua:227
 GetCharacterTable = <function> defined @DataStore/API/Core.lua:319
 GetNameOfMain = <function> defined @DataStore/API/GuildComm.lua:262
 SetDefaultLocale = <function> defined @DataStore/API/Locale.lua:35
 Frames = DataStoreFrames {
 }
 ListenTo = <function> defined @DataStore/API/Core.lua:199
 GetGuild = <function> defined @DataStore/DataStore.lua:242
 OnPlayerLogin = <function> defined @DataStore/Events/Loading.lua:50
 Print = <function> defined @DataStore/API/Core.lua:198
 ThisAccount = "Default"
 SetCheckBoxToo`

**Comment by Thaoky** [comment]
Fixed in .016 (release later today)
