### ISSUE TITLE
Enhancement Request: Add to Blizzard "AddOns Button"

### ISSUE THREAD

**Issue by JPEscher** [Thaoky/Altoholic_Retail#17]
not sure where to place a request but i noticed that this doesnt show in my blizzard add ons button as per the image below. would it be possible to add it there? it allows for hiding the button and a cleaner interface :)
![image](https://github.com/Thaoky/Altoholic_Retail/assets/46279739/b9cc8d4c-5ba2-477a-9905-ac93510e0ce5)

**Comment by Thaoky** [comment]
Implemented in .016 (release later today)
