### ISSUE TITLE
Altoholic v10.2.015 (retail): DataStore_Crafts/DataStore_Crafts_Retail.lua:265: attempt to index local 'profession' (a nil value)

### ISSUE THREAD

**Issue by R-Adrian** [Thaoky/Altoholic_Retail#19]
on a character that has Mining + Skinning as professions ... but in the Draenor Garrison has a Blacksmithing building....
~~(edit: these two do not matter)~~ edit2: they do seem to matter though /edit2

open the Blacksmithing interface from the building crafting NPC and this happens:

1x DataStore_Crafts/DataStore_Crafts_Retail.lua:265: attempt to index local 'profession' (a nil value)
[string "@DataStore_Crafts/DataStore_Crafts_Retail.lua"]:265: in function <DataStore_Crafts/DataStore_Crafts_Retail.lua:263>
[string "@DataStore_Crafts/DataStore_Crafts_Retail.lua"]:317: in function <DataStore_Crafts/DataStore_Crafts_Retail.lua:302>
[string "@DataStore_Crafts/DataStore_Crafts_Retail.lua"]:503: in function `callback'
[string "@DataStore/Events/Addon.lua"]:16: in function <DataStore/Events/Addon.lua:12>

<details>
Locals:
profession = nil
professionIndex = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'profession' (a nil value)"
C_TradeSkillUI = <table> {
 GetCraftingOperationInfo = <function> defined =[C]:-1
 IsRecipeSourceTypeFiltered = <function> defined =[C]:-1
 GetSalvagableItemIDs = <function> defined =[C]:-1
 DropPendingObliterateItemFromCursor = <function> defined =[C]:-1
 GetRecipeInfo = <function> defined =[C]:-1
 IsTradeSkillReady = <function> defined =[C]:-1
 GetRecipeItemNameFilter = <function> defined =[C]:-1
 SetRecipeItemNameFilter = <function> defined =[C]:-1
 SetInventorySlotFilter = <function> defined =[C]:-1
 GetRecipeLink = <function> defined =[C]:-1
 GetRecipeSchematic = <function> defined =[C]:-1
 GetOnlyShowSkillUpRecipes = <function> defined =[C]:-1
 GetAllRecipeIDs = <function> defined =[C]:-1
 SetOnlyShowSkillUpRecipes = <function> defined =[C]:-1
 StopRecipeRepeat = <function> defined =[C]:-1
 GetProfessionChildSkillLineID = <function> defined =[C]:-1
 IsRuneforging = <function> defined =[C]:-1
 ClearPendingObliterateItem = <function> defined =[C]:-1
 GetCategories = <function> defined =[C]:-1
 GetReagentDifficultyText = <function> defined =[C]:-1
 GetFactionSpecificOutputItem = <function> defined =[C]:-1
 GetSourceTypeFilter = <function> defined =[C]:-1
 HasFavoriteOrderRecipes = <function> defined =[C]:-1
 GetRecipeQualityItemIDs = <function> defined =[C]:-1
 IsRecipeRepeating = <function> defined =[C]:-1
 SetRecipeFavorite = <function> defined =[C]:-1
 GetOnlyShowFirstCraftRecipes = <function> defined =[C]:-1
 IsRecipeProfessionLearned = <function> defined =[C]:-1
 GetQualitiesForRecipe = <function> defined =[C]:-1
 GetAllProfessionTradeSkillLines = <function> defined =[C]:-1
 GetSubCategories = <function> defined =[C]:-1
 OpenRecipe = <function> defined =[C]:-1
 SetOnlyShowMakeableRecipes = <function> defined =[C]:-1
 IsNearProfessionSpellFocus = <function> defined =[C]:-1
 IsRecipeFavorite = <function> defined =[C]:-1
 IsRecraftItemEquipped = <function> defined =[C]:-1
 CanTradeSkillListLink = <function> defined =[C]:-1
 GetRecipeSourceText = <function> defined =[C]:-1
 IsEnchantTargetValid = <function> defined =[C]:-1
 GetProfessionSkillLineID = <function> defined =[C]:-1
 GetProfessionInfoByRecipeID = <function> defined =[C]:-1
 GetPendingObliterateItemLink = <function> defined =[C]:-1
 CloseTradeSkill = <function> defined =[C]:-1
 ClearInventorySlotFilter = <function> defined =[C]:-1
 SetRecipeCategoryFilter = <function> defined =[C]:-1
 CraftSalvage = <function> defined =[C]:-1
 GetCraftingTargetItems = <function> defined =[C]:-1
 GetEnchantItems = <function> defined =[C]:-1
 CanStoreEnchantInItem = <function> defined =[C]:-1
 GetRecipeRepeatCount = <function> defined @Blizzard_Deprecated/Deprecated_10_0_0.lua:18
 GetProfessionNameForSkillLineAbility = <function> defined =[C]:-1
 GetChildProfessionInfo = <function> defined =[C]:-1
 ObliterateItem = <function> defined =[C]:-1
 SetShowLearned = <function> defined =[C]:-1
 GetCategoryInfo = <function> defined =[C]:-1
 GetPendingObliterateItemID = <function> defined =[C]:-1
 GetOriginalCraftRecipeID = <function> defined =[C]:-1
 IsTradeSkillGuild = <function> defined =[C]:-1
 IsNPCCrafting = <function> defined =[C]:-1
 GetBaseProfessionInfo = <function> defined =[C]:-1
 IsOriginalCraftRecipeLearned = <function> defined =[C]:-1
 GetRecipeInfoForSkillLineAbility = <function> defined =[C]:-1
 GetHideUnownedFlags = <function> defined =[C]:-1
 SetShowUnlearned = <function> defined =[C]:-1
 GetGatheringOperationInfo = <function> defined =[C]:-1
 GetRecipeDescription = <function> defined =[C]:-1
 GetReagentSlotStatus = <function> defined =[C]:-1
 GetProfessionInventorySlots = <function> defined
</details>

**Comment by R-Adrian** [comment]
the main professions do not seem to matter, on another character that has Alchemy + Herbalism as professions, in the Draenor Garrison i have an Alchemist crafter NPC and the same error happens when opening the crafting interface from the NPC:

3x DataStore_Crafts/DataStore_Crafts_Retail.lua:265: attempt to index local 'profession' (a nil value)
[string "@DataStore_Crafts/DataStore_Crafts_Retail.lua"]:265: in function <DataStore_Crafts/DataStore_Crafts_Retail.lua:263>
[string "@DataStore_Crafts/DataStore_Crafts_Retail.lua"]:317: in function <DataStore_Crafts/DataStore_Crafts_Retail.lua:302>
[string "@DataStore_Crafts/DataStore_Crafts_Retail.lua"]:503: in function `callback'
[string "@DataStore/Events/Addon.lua"]:16: in function <DataStore/Events/Addon.lua:12>

<details>
Locals:
profession = nil
professionIndex = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'profession' (a nil value)"
C_TradeSkillUI = <table> {
 GetCraftingOperationInfo = <function> defined =[C]:-1
 IsRecipeSourceTypeFiltered = <function> defined =[C]:-1
 GetSalvagableItemIDs = <function> defined =[C]:-1
 DropPendingObliterateItemFromCursor = <function> defined =[C]:-1
 GetRecipeInfo = <function> defined =[C]:-1
 IsTradeSkillReady = <function> defined =[C]:-1
 GetRecipeItemNameFilter = <function> defined =[C]:-1
 SetRecipeItemNameFilter = <function> defined =[C]:-1
 SetInventorySlotFilter = <function> defined =[C]:-1
 GetRecipeLink = <function> defined =[C]:-1
 GetRecipeSchematic = <function> defined =[C]:-1
 GetOnlyShowSkillUpRecipes = <function> defined =[C]:-1
 GetAllRecipeIDs = <function> defined =[C]:-1
 SetOnlyShowSkillUpRecipes = <function> defined =[C]:-1
 StopRecipeRepeat = <function> defined =[C]:-1
 GetProfessionChildSkillLineID = <function> defined =[C]:-1
 IsRuneforging = <function> defined =[C]:-1
 ClearPendingObliterateItem = <function> defined =[C]:-1
 GetCategories = <function> defined =[C]:-1
 GetReagentDifficultyText = <function> defined =[C]:-1
 GetFactionSpecificOutputItem = <function> defined =[C]:-1
 GetSourceTypeFilter = <function> defined =[C]:-1
 HasFavoriteOrderRecipes = <function> defined =[C]:-1
 GetRecipeQualityItemIDs = <function> defined =[C]:-1
 IsRecipeRepeating = <function> defined =[C]:-1
 SetRecipeFavorite = <function> defined =[C]:-1
 GetOnlyShowFirstCraftRecipes = <function> defined =[C]:-1
 IsRecipeProfessionLearned = <function> defined =[C]:-1
 GetQualitiesForRecipe = <function> defined =[C]:-1
 GetAllProfessionTradeSkillLines = <function> defined =[C]:-1
 GetSubCategories = <function> defined =[C]:-1
 OpenRecipe = <function> defined =[C]:-1
 SetOnlyShowMakeableRecipes = <function> defined =[C]:-1
 IsNearProfessionSpellFocus = <function> defined =[C]:-1
 IsRecipeFavorite = <function> defined =[C]:-1
 IsRecraftItemEquipped = <function> defined =[C]:-1
 CanTradeSkillListLink = <function> defined =[C]:-1
 GetRecipeSourceText = <function> defined =[C]:-1
 IsEnchantTargetValid = <function> defined =[C]:-1
 GetProfessionSkillLineID = <function> defined =[C]:-1
 GetProfessionInfoByRecipeID = <function> defined =[C]:-1
 GetPendingObliterateItemLink = <function> defined =[C]:-1
 CloseTradeSkill = <function> defined =[C]:-1
 ClearInventorySlotFilter = <function> defined =[C]:-1
 SetRecipeCategoryFilter = <function> defined =[C]:-1
 CraftSalvage = <function> defined =[C]:-1
 GetCraftingTargetItems = <function> defined =[C]:-1
 GetEnchantItems = <function> defined =[C]:-1
 CanStoreEnchantInItem = <function> defined =[C]:-1
 GetRecipeRepeatCount = <function> defined @Blizzard_Deprecated/Deprecated_10_0_0.lua:18
 GetProfessionNameForSkillLineAbility = <function> defined =[C]:-1
 GetChildProfessionInfo = <function> defined =[C]:-1
 ObliterateItem = <function> defined =[C]:-1
 SetShowLearned = <function> defined =[C]:-1
 GetCategoryInfo = <function> defined =[C]:-1
 GetPendingObliterateItemID = <function> defined =[C]:-1
 GetOriginalCraftRecipeID = <function> defined =[C]:-1
 IsTradeSkillGuild = <function> defined =[C]:-1
 IsNPCCrafting = <function> defined =[C]:-1
 GetBaseProfessionInfo = <function> defined =[C]:-1
 IsOriginalCraftRecipeLearned = <function> defined =[C]:-1
 GetRecipeInfoForSkillLineAbility = <function> defined =[C]:-1
 GetHideUnownedFlags = <function> defined =[C]:-1
 SetShowUnlearned = <function> defined =[C]:-1
 GetGatheringOperationInfo = <function> defined =[C]:-1
 GetRecipeDescription = <function> defined =[C]:-1
 GetReagentSlotStatus = <function> defined =[C]:-1
 GetProfessionInventorySlots = <function> defined
</details>

**Comment by Thaoky** [comment]
I'll check that.. I'll admit I did not check the WoD npc's ..

**Comment by Thaoky** [comment]
There's something weird here. I can't reproduce it, and based on your call stack and the locals, it should crash earlier.
See, it says in the locals that "profession" and "professionIndex" are both nil, but if professionIndex was really nil, then it would have crashed at line 315.

May I ask you to add those two lines between 315 and 317 in DataStore_Crafts/DataStore_Crafts_Retail.lua, and tell me what you see ?

print("profession: " .. (profession or "nil"))
print("professionIndex: " .. (professionIndex or "nil"))

The first line should print the address of the table (or crash if it is really nil), the second one its index.

**Comment by R-Adrian** [comment]
i think i know where i messed up my testing...
i moved the buildings around... i have both engineering and alchemy buildings in the garrison and i thought i was in the alchemy one... but i am in Engineering. (on my Alchemist + Herbalist char) 

![image](https://github.com/Thaoky/Altoholic_Retail/assets/16319504/52ace4f4-d65e-4014-8736-b068976ac642)

**Comment by furball13** [comment]
I got it to blow up on my miner/skinner, at the enchanting and blacksmithing buildings.

At line 317 in DataStore_Crafts_Retail.lua I added:
	print("TradeskillName: " .. (tradeskillName or nil))
	print("ProfessionIndex: " .. (professionIndex or nil))
	print("Profession: " .. (profession or nil))

TradeskillName is what you'd expect (Enchanting, at that building). The error occurs on the next line (trying to print professionIndex):

DataStore_Crafts/DataStore_Crafts_Retail.lua:318: attempt to concatenate a nil value
[string "@DataStore_Crafts/DataStore_Crafts_Retail.lua"]:318: in function <DataStore_Crafts/DataStore_Crafts_Retail.lua:302>
[string "@DataStore_Crafts/DataStore_Crafts_Retail.lua"]:507: in function `callback'
[string "@DataStore/Events/Addon.lua"]:16: in function <DataStore/Events/Addon.lua:12>

Locals:
info = <table> {
 skillLevel = 0
 professionID = 333
 sourceCounter = 3
 isPrimaryProfession = true
 profession = 9
 skillModifier = 0
 professionName = "Enchanting"
 maxSkillLevel = 0
 expansionName = "Unknown"
}
tradeskillName = "Enchanting"
char = <table> {
 Professions = <table> {
 }
 lastUpdate = 1717354503
 Indices = <table> {
 }
 Ranks = <table> {
 }
}
professionIndex = nil
profession = nil

**Comment by Thaoky** [comment]
Hi, could you try changing lines 314-315 to this ? I think scanning the profession links is missed for some reason, this should fix it.

`	local professionIndex = char.Indices[tradeskillName]
	if not professionIndex then
		ScanProfessionLinks()
		professionIndex = char.Indices[tradeskillName]
	end

	local profession = char.Professions[professionIndex]`

**Comment by furball13** [comment]
The problem is that the game is using the Tradeskill UI to "craft" things that aren't actually a known profession (Runeforging was the same issue, but that's checked for now). In the garrison, it's NPCs making things from existing professions, but the player hasn't learned those professions. I just checked, and I also get the same error at the Tuskarr Fishing Gear crafter in Iskaara.

C_TradeSkillUI.GetBaseProfessionInfo() returns skillLevel=0 for both places (Runeforging returns 1), so it might work to add another condition to line 311:

`if not tradeskillName or tradeskillName == "UNKNOWN" or info.skillLevel == 0 or info.professionID == 960 then return end`

I don't know if there is any time that would exclude a legitimate scan though.

**Comment by Thaoky** [comment]
I made a tentative fix in .017, just uploaded, please try with it and let me know :)

**Comment by furball13** [comment]
Looks good for me. No more errors in garrison (tested blacksmith and enchanter buildings, on a miner/skinner character), or Iskaara. 👍

**Comment by R-Adrian** [comment]
looks good for me too - no more profession errors in garrison either when opening the NPC interface, so i think i can close this issue now, Thank You.

(i'm playing mostly Pandaria Remix these days and i avoided visiting Garrisons much)
