### ISSUE TITLE
Give the option to install direct from Github please?

### ISSUE THREAD

**Issue by Poisonenvy2** [Thaoky/Altoholic_Retail#25]
Hi there.  I used to download your addon from wowinterface, but it regularly seems to be out of date.  I use wowup and can also install direct from Github, but only when it's set up correctly.  Unfortunately I'm completely useless at this type of thing, so don't know how easy or hard it would be, but would it be possible for you to look into enabling the option?

This is the info from WowUp:

![image](https://github.com/user-attachments/assets/c964fba6-1d53-474b-b017-e973653595b2)
![image](https://github.com/user-attachments/assets/0d9a62dd-e0f3-4e2e-9bd8-787d1572c80b)

Link to WowUp discord: https://discord.gg/RcyqtJBm5x

Thank you

**Comment by Thaoky** [comment]
Hi, I won't support this, WoWup leeches from the work of other sides. Also the structure of my addon is way more complex than most other addons, and does not lend itself to doing this.

**Comment by Poisonenvy2** [comment]
No worries.  Thank you for considering it.  For info, Wowup do actually have an agreement with Curse, but not a problem.

**Comment by Magikh42** [comment]
> Hi, I won't support this, WoWup leeches from the work of other sides. Also the structure of my addon is way more complex than most other addons, and does not lend itself to doing this.

WoWUp is free software while Curseforge is proprietary
Both rely on open source libraries, but only one of them is itself open source
So the one that "leech" is by far Curseforge
Plus Overwolf is a huge spyware and used to install shit like cryptominers on your computer

Please don't spread misinformation
