### ISSUE TITLE
Error when transfering currency from multiple alts

### ISSUE THREAD

**Issue by nearlysober80** [Thaoky/Altoholic_Retail#30]
Able to transfer currency from first character, then when I start to transfer from a 2nd I get a UI blocking error from Altaholic and have to reload UI.

3x [ADDON_ACTION_FORBIDDEN] AddOn 'Altoholic' tried to call the protected function 'RequestCurrencyFromAccountCharacter()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: in function `RequestCurrencyFromAccountCharacter'
[string "@Blizzard_TokenUI/Blizzard_CurrencyTransfer.lua"]:331: in function <...ddOns/Blizzard_TokenUI/Blizzard_CurrencyTransfer.lua:328>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
}

**Comment by Thaoky** [comment]
Fixed in 11.0.002.
