### ISSUE TITLE
Datastore randomly losing track of the reagant bank

### ISSUE THREAD

**Issue by StormsparkPegasus** [Thaoky/Altoholic_Retail#35]
This is happening completely randomly, only since the warbank was activated in-game.  On random toons (so far I've only noticed it on level 70's), datastore seems to forget what was in the reagant bank.  Sometimes it shows it blank, sometimes it shows some items but not others.  Going to the reagant bank will temporary repopulate it, but it seems to happen about 50% of the time when you look at the reagant bank on a character in datastore.  Deleting and repopulating a character makes no difference.

**Comment by Thaoky** [comment]
Should be fixed in 11.0.002, please reopen if it is not.
