### ISSUE TITLE
Logic on "Show account bank count" option is reversed

### ISSUE THREAD

**Issue by nwferreri** [Thaoky/Altoholic_Retail#40]
When the option is checked, the count does not show.
When the option is unchecked, the count shows.

**Comment by 1armageddon1** [comment]
Similar problem here, even after full manual reinstall and deletion of files in WTF folder the problem persists.

Also for me I have to look in the warband bank every time I close the game to get the items to show in tooltips again. Swapping characters is fine, its only exiting the game that removes item counts from tooltips.

**Comment by BootleggerFinn** [comment]
I'm having a possibly related problem, the count does not show for me regardless of whether or not the option is checked or unchecked. Furthermore, if I check the option, and then reload UI, it becomes unchecked once again. I'm wondering if it's even setting the flag in the first place.

**Comment by CuddlyZombie** [comment]
I'm having a possibly related problem, the count does not show for me regardless of whether or not the option is checked or unchecked. Furthermore, if I check the option, and then reload UI, it becomes unchecked once again. I'm wondering if it's even setting the flag in the first place.

**Comment by Thaoky** [comment]
Fixed in .003
