### ISSUE TITLE
bug   attempt to perform arithmetic on local 'xpMax' 

### ISSUE THREAD

**Issue by Addonman** [Thaoky/Altoholic_Retail#44]
Message: ...AddOns/DataStore_Characters/DataStore_Characters.lua line 321:
   attempt to perform arithmetic on local 'xpMax' (a nil value)
Debug:
   [string "@Interface/AddOns/DataStore_Characters/DataStore_Characters.lua"]:321:
      ...AddOns/DataStore_Characters/DataStore_Characters.lua:282
   [string "=(tail call)"]: ?
   [string "@Interface/AddOns/Altoholic_Summary/Services/Characters.lua"]:355:
      ...ace/AddOns/Altoholic_Summary/Services/Characters.lua:347
   [string "=(tail call)"]: ?
   [string "=[C]"]: sort()
   [string "@Interface/AddOns/Altoholic_Summary/Services/Characters.lua"]:381: Sort()
   [string "@Interface/AddOns/Altoholic_Summary/TabSummary.lua"]:680: Update()
   [string "@Interface/AddOns/Altoholic_Summary/TabSummary.lua"]:789: callback()
   [string "@Interface/AddOns/AddonFactory/Templates/AuctionHouseUI/CategoriesList.lua"]:58: Button_OnClick()
   [string "@Interface/AddOns/Altoholic_Summary/TabSummary.lua"]:939: callback()
   [string "@Interface/AddOns/DataStore/Events/Loading.lua"]:25:
      Interface/AddOns/DataStore/Events/Loading.lua:18
   [string "=[C]"]: ?
   [string "=[C]"]: LoadAddOn()
   [string "*Main.xml:65_OnShow"]:2:
      [string "*Main.xml:65_OnShow"]:1
   [string "=[C]"]: Show()
   [string "@Interface/AddOns/AddonFactory/Templates/AuctionHouseUI/Main.lua"]:87: ToggleUI()
   [string "*Main.xml:31_OnClick"]:2:
      [string "*Main.xml:31_OnClick"]:1
Locals:

**Comment by Addonman** [comment]
Message: ...dOns/DataStore_Reputations/DataStore_Reputations.lua line 35:
   attempt to index local 'info' (a nil value)
Debug:
   [string "=(tail call)"]: ?
   [string "=(tail call)"]: ?
   [string "=[C]"]: ?
   [string "@Interface/AddOns/DataStore_Reputations/DataStore_Reputations.lua"]:35:
      ...dOns/DataStore_Reputations/DataStore_Reputations.lua:33
   [string "@Interface/AddOns/DataStore_Reputations/DataStore_Reputations.lua"]:298:
      ...dOns/DataStore_Reputations/DataStore_Reputations.lua:294
   [string "@Interface/AddOns/DataStore_Reputations/DataStore_Reputations.lua"]:437:
      ...dOns/DataStore_Reputations/DataStore_Reputations.lua:436
   [string "@Interface/AddOns/DataStore_Reputations/DataStore_Reputations.lua"]:521: callback()
   [string "@Interface/AddOns/DataStore/Events/Addon.lua"]:17:
      Interface/AddOns/DataStore/Events/Addon.lua:13

**Comment by Thaoky** [comment]
The reputations one is fixed in .003. 
The first one: did you properly clear your SV files since the DB change in 10.2 ?

**Comment by Addonman** [comment]
i did it multiple times through curse forge. Does deleting saved variables of altoholic and also datastore does the trick or do i have to deleted for every module as well?

**Comment by Thaoky** [comment]
Whn clearing the SV, you should clear the DataStore* files, Altoholic* mostly contains UI options, which in this case have no effect.
I'll close the issue, please reopen if it still happens.
