### ISSUE TITLE
Reputation spam back

### ISSUE THREAD

**Issue by JamesMDenton** [Thaoky/Altoholic_Retail#45]
Should be fixed in 11.0.002, please reopen if it is not.

_Originally posted by @Thaoky in https://github.com/Thaoky/Altoholic_Retail/issues/36#issuecomment-2288235258_
            

Can't reopen, so making new issue.

**Comment by razgriz5000** [comment]
same, for a few hours it wasnt a problem after then it started again.  it might be related to the hotfix that got pushed yesterday, im not sure.  

`Message: ...dOns/DataStore_Reputations/DataStore_Reputations.lua:35: attempt to index local 'info' (a nil value)
Time: Sat Aug 24 22:45:53 2024
Count: 1
Stack: ...dOns/DataStore_Reputations/DataStore_Reputations.lua:35: attempt to index local 'info' (a nil value)
[string "@Interface/AddOns/DataStore_Reputations/DataStore_Reputations.lua"]:35: in function <...dOns/DataStore_Reputations/DataStore_Reputations.lua:33>
[string "@Interface/AddOns/DataStore_Reputations/DataStore_Reputations.lua"]:298: in function <...dOns/DataStore_Reputations/DataStore_Reputations.lua:294>
[string "@Interface/AddOns/DataStore_Reputations/DataStore_Reputations.lua"]:437: in function <...dOns/DataStore_Reputations/DataStore_Reputations.lua:436>
[string "@Interface/AddOns/DataStore_Reputations/DataStore_Reputations.lua"]:521: in function `callback'
[string "@Interface/AddOns/DataStore/Events/Addon.lua"]:17: in function <Interface/AddOns/DataStore/Events/Addon.lua:13>

Locals: index = 5
info = nil
(*temporary) = nil
(*temporary) = 5
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'info' (a nil value)"
C_Reputation = <table> {
}
`

**Comment by Thaoky** [comment]
Fixed in .003
