### ISSUE TITLE
bug odd behaviour

### ISSUE THREAD

**Issue by Addonman** [Thaoky/Altoholic_Retail#47]
I reseted all. And logged in on like 5 chars. Odd is that i could only see 2 of them on summary list. Then i checked level filter on account summary. It was set on all, but only when i checked 70+ filter i could see all my char. After that  i set all filter and now i can  see all 5 chars as well.

**Comment by Stoutmayer** [comment]
I noticed the same issue on the Summary page, your character shows up on the character tab but not summary, I believe they have to increase the level to 80. Check and see if it only your toons that are above 70.

**Comment by Addonman** [comment]
All my chars i was checking are 70+.

**Comment by evoelise** [comment]
Many thanks for posting this. I spent ages trying to work out why my main and one of my alts was not shown.
Selecting 70+ shows the missing ones.

**Comment by Thaoky** [comment]
Same as #50
