### ISSUE TITLE
Character level filter

### ISSUE THREAD

**Issue by Kersplat314** [Thaoky/Altoholic_Retail#50]
The number one issue on Discord is characters over 70 not being shown even though the level filter is set to All. The problem is that the level range for All is still set to 1 to 70 in tabsummary.lua on a fresh installation/altoholic data wipe. It's easily fixed by changing the level filter to all again but its causing confusion. I'd probably go as far as forcing the maximum level to the correct value if the level range is All and it's not correct.

**Comment by vaisest** [comment]
Can confirm this is still an issue. I nuked all my Datastore and Altoholic, before seeing your issue. Changing the level filter to anything and then back to all worked.

**Comment by Thaoky** [comment]
Side effect of the database redesign, won't be fixed
