### ISSUE TITLE
Profession equipment

### ISSUE THREAD

**Issue by Ghordian** [Thaoky/Altoholic_Retail#8]
I know we are at the end of this expansion, but I still think we need a tool to be able to see what profession equipment each of our alters/mains has and whether we are interested in upgrading it, replacing it or just leaving it as it is.
To do this, I think the best place is to add a new category (Profession Equipment) in the "Grids" section.
The current "Equipment" category could also be expanded, but as there are so many slots (from the current 18 to a total of 29), I think it would be more concentrated in its own category.

![image](https://github.com/Thaoky/Altoholic_Retail/assets/11998562/ce323a49-f6d7-45da-8eb0-83cc16fde45a)

**Comment by Thaoky** [comment]
This has been added in the next version (currently in release candidate)
